repos:
  - repo: https://gitlab.com/vojko.pribudic.foss/pre-commit-update
    rev: v0.9.0
    hooks:
      # Update pre-commit scripts
      - id: pre-commit-update

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.9.13
    hooks:
      # Update the uv lockfile
      - id: uv-lock

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.21.2
    hooks:
      # Upgrade syntax for newer versions of the language
      - id: pyupgrade
        args: [--py312-plus]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      # Prevent giant files from being committed
      - id: check-added-large-files
      # Check whether files parse as valid python
      - id: check-ast
      # Require literal syntax for empty or zero Python builtin types
      - id: check-builtin-literals
      # Check for files with conflict on a case-insensitive filesystem
      - id: check-case-conflict
      # Checks that non-binary executables have a proper shebang
      - id: check-executables-have-shebangs
      # Check for files that cannot be created on Windows
      - id: check-illegal-windows-names
      # Attempts to load all json files to verify syntax
      - id: check-json
      # Checks that scripts with shebangs are executable
      - id: check-shebang-scripts-are-executable
      # Checks for symlinks which do not point to anything
      - id: check-symlinks
      # Attempts to load all TOML files to verify syntax
      - id: check-toml
      # Attempts to load all yaml files to verify syntax
      - id: check-yaml
      # Makes sure files end in a newline and only a newline
      - id: end-of-file-fixer
      # Removes UTF-8 byte order marker
      - id: fix-byte-order-marker
      # Replaces or checks mixed line ending
      - id: mixed-line-ending
      # Verifies that test files are named correctly
      - id: name-tests-test
        args: [--pytest-test-first]
      # Protect specific branches from direct checkins
      - id: no-commit-to-branch
        args: [-b, dev]
      # Trims trailing whitespace
      - id: trailing-whitespace

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.37.1
    hooks:
      # Lint YAML files
      - id: yamllint

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.7
    hooks:
      # Run the linter
      - id: ruff-check
        args: [--fix, --show-fixes, --exit-non-zero-on-fix]
      # Run the formatter
      - id: ruff-format

  # local hook used to avoid repeating dependencies list
  - repo: local
    hooks:
      # Check type annotations
      - id: mypy
        name: mypy
        entry: mypy
        require_serial: true
        language: system
        'types_or': [python, pyi]

  - repo: https://github.com/fpgmaas/deptry.git
    rev: 0.24.0
    hooks:
      # Check for problems in dependency declarations
      - id: deptry
        args: ["src"]

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      # Fix common misspellings in text files
      - id: codespell
        additional_dependencies:
          - tomli

  - repo: https://github.com/jendrikseipp/vulture
    rev: v2.14
    hooks:
      # Finds unused code
      - id: vulture

  - repo: https://github.com/pappasam/toml-sort
    rev: v0.24.3
    hooks:
      # Sort and format toml files
      - id: toml-sort
        args: ["pyproject.toml"]
